# Generated by Django 6.0.3 on 2026-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_due_date_alter_rating_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_borrows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
