# Generated by Django 6.0.3 on 2026-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_rating_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
